In [49]:
# Paquetes necesarios
install.packages("faraway")
library(faraway)
install.packages("nnet")
library(nnet)

# Cargar datos
data(nes96)

# Revisar estructura
str(nes96)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

'data.frame':	944 obs. of  10 variables:
 $ popul : int  0 190 31 83 640 110 100 31 180 2800 ...
 $ TVnews: int  7 1 7 4 7 3 7 1 7 0 ...
 $ selfLR: Ord.factor w/ 7 levels "extLib"<"Lib"<..: 7 3 2 3 5 3 5 5 4 3 ...
 $ ClinLR: Ord.factor w/ 7 levels "extLib"<"Lib"<..: 1 3 2 4 6 4 6 4 6 3 ...
 $ DoleLR: Ord.factor w/ 7 levels "extLib"<"Lib"<..: 6 5 6 5 4 6 4 5 3 7 ...
 $ PID   : Ord.factor w/ 7 levels "strDem"<"weakDem"<..: 7 2 2 2 1 2 2 5 4 1 ...
 $ age   : int  36 20 24 28 68 21 77 21 31 39 ...
 $ educ  : Ord.factor w/ 7 levels "MS"<"HSdrop"<..: 3 4 6 6 6 4 4 4 4 3 ...
 $ income: Ord.factor w/ 24 levels "$3Kminus"<"$3K-$5K"<..: 1 1 1 1 1 1 1 1 1 1 ...
 $ vote  : Factor w/ 2 levels "Clinton","Dole": 2 1 1 1 1 1 1 1 1 1 ...

In [50]:
head(nes96)

  popul TVnews selfLR ClinLR DoleLR PID     age educ  income   vote
1   0   7      extCon extLib Con    strRep  36  HS    $3Kminus Dole
2 190   1      sliLib sliLib sliCon weakDem 20  Coll  $3Kminus Clinton
3  31   7      Lib    Lib    Con    weakDem 24  BAdeg $3Kminus Clinton
4  83   4      sliLib Mod    sliCon weakDem 28  BAdeg $3Kminus Clinton
5 640   7      sliCon Con    Mod    strDem  68  BAdeg $3Kminus Clinton
6 110   3      sliLib Mod    Con    weakDem 21  Coll  $3Kminus Clinton

In [51]:
table(nes96$PID)

 strDem weakDem  indDem  indind  indRep weakRep  strRep
    200     180     108      37      94     150     175

In [52]:
#nes96$PID <- factor(nes96$PID)

# Ver categoría de referencia
levels(nes96$PID)

[1] "strDem"  "weakDem" "indDem"  "indind"  "indRep"  "weakRep" "strRep"

In [53]:
nes96$PID3 <- with(nes96,
  ifelse(PID %in% c("strDem","weakDem","indDem"), "Democrat",
  ifelse(PID %in% c("strRep","weakRep","indRep"), "Republican",
         "Independent"))
)

nes96$PID3 <- factor(nes96$PID3,
                     levels = c("Democrat","Republican","Independent"))

table(nes96$PID3)

   Democrat  Republican Independent
        488         419          37

In [54]:
levels(nes96$PID3)

[1] "Democrat"    "Republican"  "Independent"

In [55]:
head(nes96)

  popul TVnews selfLR ClinLR DoleLR PID     age educ  income   vote
1   0   7      extCon extLib Con    strRep  36  HS    $3Kminus Dole
2 190   1      sliLib sliLib sliCon weakDem 20  Coll  $3Kminus Clinton
3  31   7      Lib    Lib    Con    weakDem 24  BAdeg $3Kminus Clinton
4  83   4      sliLib Mod    sliCon weakDem 28  BAdeg $3Kminus Clinton
5 640   7      sliCon Con    Mod    strDem  68  BAdeg $3Kminus Clinton
6 110   3      sliLib Mod    Con    weakDem 21  Coll  $3Kminus Clinton
  PID3
1 Republican
2 Democrat
3 Democrat
4 Democrat
5 Democrat
6 Democrat

In [56]:
#Fijamos como categoría de referencia "Democrat"
library(forcats)
nes96$PID3 <- fct_relevel(nes96$PID3, "Democrat")

#Otra forma de hacerlo
#levels(nes96$PID3)
#nes96$PID3 <- factor(nes96$PID3,
#                    levels = c("Democrat", "Republican", "Independent")) # Al dejar primero "Democrat" lo estamos fijando

In [57]:
mod_mult <- multinom(PID3 ~ age + educ + income, data = nes96)

# weights:  96 (62 variable)
initial  value 1037.090001
iter  10 value 742.881119
iter  20 value 732.255441
iter  30 value 729.993746
iter  40 value 729.463662
iter  50 value 729.257555
iter  60 value 729.250200
final  value 729.249879
converged

In [58]:
summary(mod_mult)

Call:
multinom(formula = PID3 ~ age + educ + income, data = nes96)

Coefficients:
            (Intercept)         age educHSdrop    educHS  educColl educCCdeg
Republican    -2.499502 0.010133009  0.7293974  1.068064  1.310622  1.128252
Independent  -17.195741 0.004996971 14.9094824 14.691340 14.610315 14.270396
            educBAdeg  educMAdeg income$3K-$5K income$5K-$7K income$7K-$9K
Republican   1.190927  0.8455374     -1.394611     0.3588026    -0.3781631
Independent 13.876481 13.8352763    -14.440778   -14.2200352    -0.3238413
            income$9K-$10K income$10K-$11K income$11K-$12K income$12K-$13K
Republican       0.6410272       0.7456588       0.7726017       0.5449322
Independent      1.5480950     -13.2662179     -12.4274337       1.0673346
            income$13K-$14K income$14K-$15K income$15K-$17K income$17K-$20K
Republican        0.7638633      -0.3437016       0.3227693       0.4443445
Independent       1.1158354       0.7413504     -14.0624515      -0.6204797
            income$20K-$22K income$22K-$25K income$25K-$30K income$30K-$35K
Republican        0.1898005      -0.1720251       0.5101885       0.6986622
Independent      -0.5315948      -0.8400122     -17.4011059     -17.4944431
            income$35K-$40K income$40K-$45K income$45K-$50K income$50K-$60K
Republican         0.872929       0.8177070       0.4560368       1.1620101
Independent        0.225551      -0.6240323      -0.1430574      -0.4526262
            income$60K-$75K income$75K-$90K income$90K-$105K income$105Kplus
Republican        1.2710690       1.2706677         1.533146       1.2972128
Independent       0.9170345      -0.2568064         1.478595       0.9923377

Std. Errors:
            (Intercept)         age educHSdrop    educHS  educColl educCCdeg
Republican    0.8972380 0.004449968  0.7567165 0.7095183 0.7137590 0.7341698
Independent   0.9808313 0.011161808  0.6298970 0.3582310 0.3739295 0.5690456
            educBAdeg educMAdeg income$3K-$5K income$5K-$7K income$7K-$9K
Republican  0.7162574 0.7278052  1.173705e+00  7.427073e-01     0.7828994
Independent 0.4385088 0.5407483  1.115914e-05  1.472628e-05     1.4901824
            income$9K-$10K income$10K-$11K income$11K-$12K income$12K-$13K
Republican       0.7620441    0.7738128867    8.176207e-01       0.7518183
Independent      1.2577985    0.0000228256    3.953243e-05       1.3117760
            income$13K-$14K income$14K-$15K income$15K-$17K income$17K-$20K
Republican        0.8762948       0.8504544    6.964619e-01       0.6425688
Independent       1.5505318       1.3194845    2.056943e-05       1.4791397
            income$20K-$22K income$22K-$25K income$25K-$30K income$30K-$35K
Republican        0.6881435       0.6491916    5.897337e-01    5.860832e-01
Independent       1.4823587       1.4671269    1.832327e-06    1.511633e-06
            income$35K-$40K income$40K-$45K income$45K-$50K income$50K-$60K
Republican        0.5934037       0.6095632        0.608720       0.5708263
Independent       1.2134821       1.4671132        1.279401       1.2758247
            income$60K-$75K income$75K-$90K income$90K-$105K income$105Kplus
Republican        0.5733107       0.6067882         0.625182       0.5978488
Independent       1.1319956       1.4767153         1.204565       1.2059825

Residual Deviance: 1458.5
AIC: 1582.5

In [59]:
options(contrasts = c("contr.treatment", "contr.treatment")) # elimina los contrastes polinomiales
mod_mult <- multinom(PID3 ~ age + educ + income, data = nes96)
summary(mod_mult)

# weights:  96 (62 variable)
initial  value 1037.090001
iter  10 value 742.881119
iter  20 value 732.255441
iter  30 value 729.993746
iter  40 value 729.463662
iter  50 value 729.257555
iter  60 value 729.250200
final  value 729.249879
converged

Call:
multinom(formula = PID3 ~ age + educ + income, data = nes96)

Coefficients:
            (Intercept)         age educHSdrop    educHS  educColl educCCdeg
Republican    -2.499502 0.010133009  0.7293974  1.068064  1.310622  1.128252
Independent  -17.195741 0.004996971 14.9094824 14.691340 14.610315 14.270396
            educBAdeg  educMAdeg income$3K-$5K income$5K-$7K income$7K-$9K
Republican   1.190927  0.8455374     -1.394611     0.3588026    -0.3781631
Independent 13.876481 13.8352763    -14.440778   -14.2200352    -0.3238413
            income$9K-$10K income$10K-$11K income$11K-$12K income$12K-$13K
Republican       0.6410272       0.7456588       0.7726017       0.5449322
Independent      1.5480950     -13.2662179     -12.4274337       1.0673346
            income$13K-$14K income$14K-$15K income$15K-$17K income$17K-$20K
Republican        0.7638633      -0.3437016       0.3227693       0.4443445
Independent       1.1158354       0.7413504     -14.0624515      -0.6204797
            income$20K-$22K income$22K-$25K income$25K-$30K income$30K-$35K
Republican        0.1898005      -0.1720251       0.5101885       0.6986622
Independent      -0.5315948      -0.8400122     -17.4011059     -17.4944431
            income$35K-$40K income$40K-$45K income$45K-$50K income$50K-$60K
Republican         0.872929       0.8177070       0.4560368       1.1620101
Independent        0.225551      -0.6240323      -0.1430574      -0.4526262
            income$60K-$75K income$75K-$90K income$90K-$105K income$105Kplus
Republican        1.2710690       1.2706677         1.533146       1.2972128
Independent       0.9170345      -0.2568064         1.478595       0.9923377

Std. Errors:
            (Intercept)         age educHSdrop    educHS  educColl educCCdeg
Republican    0.8972380 0.004449968  0.7567165 0.7095183 0.7137590 0.7341698
Independent   0.9808313 0.011161808  0.6298970 0.3582310 0.3739295 0.5690456
            educBAdeg educMAdeg income$3K-$5K income$5K-$7K income$7K-$9K
Republican  0.7162574 0.7278052  1.173705e+00  7.427073e-01     0.7828994
Independent 0.4385088 0.5407483  1.115914e-05  1.472628e-05     1.4901824
            income$9K-$10K income$10K-$11K income$11K-$12K income$12K-$13K
Republican       0.7620441    0.7738128867    8.176207e-01       0.7518183
Independent      1.2577985    0.0000228256    3.953243e-05       1.3117760
            income$13K-$14K income$14K-$15K income$15K-$17K income$17K-$20K
Republican        0.8762948       0.8504544    6.964619e-01       0.6425688
Independent       1.5505318       1.3194845    2.056943e-05       1.4791397
            income$20K-$22K income$22K-$25K income$25K-$30K income$30K-$35K
Republican        0.6881435       0.6491916    5.897337e-01    5.860832e-01
Independent       1.4823587       1.4671269    1.832327e-06    1.511633e-06
            income$35K-$40K income$40K-$45K income$45K-$50K income$50K-$60K
Republican        0.5934037       0.6095632        0.608720       0.5708263
Independent       1.2134821       1.4671132        1.279401       1.2758247
            income$60K-$75K income$75K-$90K income$90K-$105K income$105Kplus
Republican        0.5733107       0.6067882         0.625182       0.5978488
Independent       1.1319956       1.4767153         1.204565       1.2059825

Residual Deviance: 1458.5
AIC: 1582.5

In [60]:
coeficientes <- summary(mod_mult)$coefficients
errores <- summary(mod_mult)$standard.errors

coeficientes
errores

            (Intercept) age         educHSdrop educHS    educColl  educCCdeg
Republican   -2.499502  0.010133009  0.7293974  1.068064  1.310622  1.128252
Independent -17.195741  0.004996971 14.9094824 14.691340 14.610315 14.270396
            educBAdeg educMAdeg  income$3K-$5K income$5K-$7K ⋯ income$25K-$30K
Republican   1.190927  0.8455374  -1.394611      0.3588026   ⋯   0.5101885
Independent 13.876481 13.8352763 -14.440778    -14.2200352   ⋯ -17.4011059
            income$30K-$35K income$35K-$40K income$40K-$45K income$45K-$50K
Republican    0.6986622     0.872929         0.8177070       0.4560368
Independent -17.4944431     0.225551        -0.6240323      -0.1430574
            income$50K-$60K income$60K-$75K income$75K-$90K income$90K-$105K
Republican   1.1620101      1.2710690        1.2706677      1.533146
Independent -0.4526262      0.9170345       -0.2568064      1.478595
            income$105Kplus
Republican  1.2972128
Independent 0.9923377

            (Intercept) age         educHSdrop educHS    educColl  educCCdeg
Republican  0.8972380   0.004449968 0.7567165  0.7095183 0.7137590 0.7341698
Independent 0.9808313   0.011161808 0.6298970  0.3582310 0.3739295 0.5690456
            educBAdeg educMAdeg income$3K-$5K income$5K-$7K ⋯ income$25K-$30K
Republican  0.7162574 0.7278052 1.173705e+00  7.427073e-01  ⋯ 5.897337e-01
Independent 0.4385088 0.5407483 1.115914e-05  1.472628e-05  ⋯ 1.832327e-06
            income$30K-$35K income$35K-$40K income$40K-$45K income$45K-$50K
Republican  5.860832e-01    0.5934037       0.6095632       0.608720
Independent 1.511633e-06    1.2134821       1.4671132       1.279401
            income$50K-$60K income$60K-$75K income$75K-$90K income$90K-$105K
Republican  0.5708263       0.5733107       0.6067882       0.625182
Independent 1.2758247       1.1319956       1.4767153       1.204565
            income$105Kplus
Republican  0.5978488
Independent 1.2059825

In [61]:
prob_hat <- fitted(mod_mult)

head(prob_hat)

  Democrat  Republican Independent
1 0.6934856 0.2386698  0.06784461
2 0.6866863 0.2561230  0.05719066
3 0.7218207 0.2487366  0.02944263
4 0.7140495 0.2562368  0.02971366
5 0.6293197 0.3386983  0.03198199
6 0.6847041 0.2579846  0.05731124

In [62]:
head(rowSums(prob_hat))

1 2 3 4 5 6
1 1 1 1 1 1

In [63]:
prob_hat[1, ]

   Democrat  Republican Independent
 0.69348559  0.23866979  0.06784461

In [64]:
pred_clase <- predict(mod_mult, type = "class")

table(Observado = nes96$PID3, Predicho = pred_clase)

             Predicho
Observado     Democrat Republican Independent
  Democrat         322        166           0
  Republican       197        222           0
  Independent       17         20           0

In [65]:
summary(prob_hat)

    Democrat        Republican       Independent
 Min.   :0.2425   Min.   :0.05209   Min.   :0.00000
 1st Qu.:0.4119   1st Qu.:0.36411   1st Qu.:0.01209
 Median :0.5059   Median :0.46485   Median :0.02867
 Mean   :0.5170   Mean   :0.44385   Mean   :0.03919
 3rd Qu.:0.6133   3rd Qu.:0.54326   3rd Qu.:0.05287
 Max.   :0.9479   Max.   :0.67901   Max.   :0.29059

In [66]:
mean(pred_clase == nes96$PID3)

[1] 0.5762712

In [67]:
#install.packages("caret")
library(caret)

# Asegurarse que observado y predicho tengan los mismos niveles
pred_clase <- factor(pred_clase, levels = levels(nes96$PID3))

# Matriz de confusión y medidas
confusionMatrix(
  data = pred_clase,
  reference = nes96$PID3
)

Confusion Matrix and Statistics

             Reference
Prediction    Democrat Republican Independent
  Democrat         322        197          17
  Republican       166        222          20
  Independent        0          0           0

Overall Statistics

               Accuracy : 0.5763
                 95% CI : (0.544, 0.608)
    No Information Rate : 0.5169
    P-Value [Acc > NIR] : 0.0001455

                  Kappa : 0.1767

 Mcnemar's Test P-Value : 1.266e-08

Statistics by Class:

                     Class: Democrat Class: Republican Class: Independent
Sensitivity                   0.6598            0.5298            0.00000
Specificity                   0.5307            0.6457            1.00000
Pos Pred Value                0.6007            0.5441                NaN
Neg Pred Value                0.5931            0.6325            0.96081
Prevalence                    0.5169            0.4439            0.03919
Detection Rate                0.3411            0.2352            0.00000
Detection Prevalence          0.5678            0.4322            0.00000
Balanced Accuracy             0.5953            0.5878            0.50000

In [68]:
mod_null <- multinom(PID3 ~ 1, data = nes96)

# weights:  6 (2 variable)
initial  value 1037.090001
final  value 782.173305
converged

In [69]:
logLik(mod_null)
logLik(mod_mult)

'log Lik.' -782.1733 (df=2)

'log Lik.' -729.2499 (df=62)

In [70]:
LR <- 2 * (as.numeric(logLik(mod_mult)) - as.numeric(logLik(mod_null)))
LR

[1] 105.8469

In [71]:
gl <- attr(logLik(mod_mult), "df") - attr(logLik(mod_null), "df")
gl

[1] 60

In [72]:
pvalor <- pchisq(LR, df = gl, lower.tail = FALSE)
pvalor

[1] 0.0002405285

In [73]:
if(pvalor < 0.05){
  "El modelo con covariables mejora significativamente respecto al modelo nulo."
} else {
  "No hay evidencia suficiente de que las covariables mejoren el modelo nulo."
}

[1] "El modelo con covariables mejora significativamente respecto al modelo nulo."

In [74]:
deviance(mod_mult)
deviance(mod_null)

[1] 1458.5

[1] 1564.347

In [75]:
deviance(mod_null) - deviance(mod_mult)

[1] 105.8469